name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: install libomp for clang
      sudo apt-get install libomp-dev
      
    - name: install cmake
      run: sudo apt-get install cmake

    - name: install google-benchmark
      run: sudo apt-get install libbenchmark-dev

    - name: install google-test
      run: sudo apt-get install libgtest-dev
    
#     Dropped Support Currently (will bring back in the future | maybe)
#     - name: install crypto++
#       run: sudo apt-get install libcrypto++-dev libcrypto++-doc libcrypto++-utils
      
    - uses: actions/checkout@v2
    
    - name: build and run tests
      run: make test
