name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  clang-ubuntu:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: install libomp for clang
      run: sudo apt-get install libomp-dev

    - name: build and run tests for clang
      run: make test CXX=clang++

  clang-macos:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: install llvm
      run: brew install llvm

    - name: install libomp for clang
      run: brew install libomp

    - name: build and run tests for clang
      run: make test CXX=clang++

  clang-windows:

    runs-on: windows-2019
    
    steps:
    - uses: actions/checkout@v3

    - name: install llvm
      run: brew install llvm

    - name: install libomp for clang
      run: brew install libomp

    - name: build and run tests for clang
      run: make test CXX=clang++